import './globals.css';
import type { Metadata } from "next";
import AppShell from './AppShell';

export const metadata: Metadata = {
  title: "A4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}